<?php
return [
    'adminEmail' => 'admin@example.com',
    'supportEmail' => 'aleruiz-facilitator@softok2.com',
    'user.passwordResetTokenExpire' => 3600,
    'moneda.pago' => 'USD',
    'moneda.pago.id' => 1,
    //'categoria_img_baseurl' => 'http://local.beautydate.local.media/categoria',
    //'categoria_img_baseurl' => 'http://local.media.beautydate.softok2.com/categoria',
    //'salon_img_baseurl' => 'http://local.media.beautydate.softok2.com/salones',
    //'salon_img_baseurl' => 'http://beautydate.local.media/salones',
	'categoria_img_baseurl' => 'http://192.168.172.1/beautydate/media/categoria',
    'salon_img_baseurl' => 'http://192.168.172.1/beautydate/media/salones',
    'url_paypal_reponse_ok' => 'http://salones.beautydate.mx/payresponse.php',
    'url_paypal_reponse_cancel' => 'http://salones.beautydate.mx/payresponse-cancel.php',
    'url_paypal_reponse_ok_now' => 'http://salones.beautydate.mx/index.php?r=site/payment-done',
    'url_paypal_reponse_cancel_now' => 'http://salones.beautydate.mx/index.php?r=site/payment-cancel',
    'salones_img_path' => '/../../media/salones',
    'paypal-business-id' => 'aleruiz.cu-facilitator@gmail.com',
    'url_paypal' =>'https://www.sandbox.paypal.com/cgi-bin/webscr',
    //'url_paypal' =>'https://www.sandbox.paypal.com/cgi-bin/webscr',
];
